package com.eventplatform.auth.audit;

public enum SecurityEventType {
    REGISTRATION_SUCCESS,
    REGISTRATION_REJECTED,
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    OAUTH_LOGIN_SUCCESS,
    OAUTH_LOGIN_FAILURE,
    REFRESH_ROTATED,
    REFRESH_REJECTED,
    REFRESH_REUSE_DETECTED,
    SESSION_REVOKED,
    ALL_SESSIONS_REVOKED,
    ROLES_CHANGED
}
