package com.eventplatform.payment;

import static org.assertj.core.api.Assertions.*;

import com.eventplatform.payment.api.*; import com.eventplatform.payment.application.*; import com.eventplatform.payment.domain.*; import com.eventplatform.payment.security.AuthenticatedActor;
import java.math.BigDecimal; import java.nio.charset.StandardCharsets; import java.time.*; import java.util.*; import javax.crypto.Mac; import javax.crypto.spec.SecretKeySpec;
import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.test.context.ActiveProfiles;

@ActiveProfiles("test") @SpringBootTest
class PaymentRefundFailureIntegrationTest {
 @Autowired PaymentApplicationService payments; @Autowired PaymentWebhookService webhooks; @Autowired RefundApplicationService refunds;
 @Autowired BookingPaymentOrderRepository orders; @Autowired PaymentRepository paymentRepository; @Autowired PaymentAttemptRepository attempts;
 @Autowired PaymentTransactionRepository transactions; @Autowired ProviderWebhookEventRepository webhookEvents; @Autowired PaymentTicketProjectionRepository tickets;
 @Autowired JdbcTemplate jdbc; private final RequestContext context=new RequestContext("phase5-test",null);
 private UUID attendee; private UUID organizer; private UUID booking;

 @BeforeEach void clean(){jdbc.update("delete from payment_outbox_messages");jdbc.update("delete from processed_integration_events");jdbc.update("delete from payment_transactions");jdbc.update("delete from refunds");jdbc.update("delete from payment_attempts");jdbc.update("delete from provider_webhook_events");jdbc.update("delete from payment_ticket_projections");jdbc.update("delete from payments");jdbc.update("delete from booking_payment_orders");attendee=UUID.randomUUID();organizer=UUID.randomUUID();booking=seedOrder(2);}

 @Test void paymentSucceedsExactlyOnceDespiteDuplicateRequest(){Payment first=payments.process(booking,attendee,"pay-once","sandbox-success",context);Payment duplicate=payments.process(booking,attendee,"pay-once","sandbox-success",context);assertThat(duplicate.getId()).isEqualTo(first.getId());assertThat(first.getStatus()).isEqualTo(PaymentStatus.SUCCEEDED);assertThat(attempts.findAllByPaymentIdOrderByCreatedAt(first.getId())).hasSize(1);assertThat(transactions.findAllByPaymentIdOrderByOccurredAt(first.getId())).hasSize(1);assertThat(jdbc.queryForObject("select count(*) from payment_outbox_messages where event_type='event-platform.payment.succeeded.v1'",Long.class)).isEqualTo(1);}

 @Test void paymentFailureIsFinalAndPublished(){Payment payment=payments.process(booking,attendee,"pay-fail","sandbox-failure",context);assertThat(payment.getStatus()).isEqualTo(PaymentStatus.FAILED);assertThat(payment.getFailureCode()).isEqualTo("PAYMENT_DECLINED");assertThat(jdbc.queryForObject("select count(*) from payment_outbox_messages where event_type='event-platform.payment.failed.v1'",Long.class)).isEqualTo(1);}

 @Test void reconciliationRepairsProcessingPayment(){Payment payment=payments.process(booking,attendee,"pay-reconcile","sandbox-processing-then-success",context);assertThat(payment.getStatus()).isEqualTo(PaymentStatus.PROCESSING);Payment repaired=payments.verify(payment,context);assertThat(repaired.getStatus()).isEqualTo(PaymentStatus.SUCCEEDED);assertThat(jdbc.queryForObject("select count(*) from payment_outbox_messages where event_type='event-platform.payment.succeeded.v1'",Long.class)).isEqualTo(1);}

 @Test void duplicateAndOutOfOrderSignedWebhooksAreMonotonic(){Payment payment=payments.process(booking,attendee,"pay-webhook","sandbox-processing",context);String success="{\"eventId\":\"evt-success\",\"eventType\":\"payment.updated\",\"providerPaymentId\":\""+payment.getProviderPaymentId()+"\",\"status\":\"SUCCEEDED\"}";assertThat(webhooks.consume("fake",success,sign(success),context)).isTrue();assertThat(webhooks.consume("fake",success,sign(success),context)).isFalse();String lateFailure="{\"eventId\":\"evt-late-failure\",\"eventType\":\"payment.updated\",\"providerPaymentId\":\""+payment.getProviderPaymentId()+"\",\"status\":\"FAILED\"}";webhooks.consume("fake",lateFailure,sign(lateFailure),context);assertThat(paymentRepository.findById(payment.getId()).orElseThrow().getStatus()).isEqualTo(PaymentStatus.SUCCEEDED);assertThat(webhookEvents.count()).isEqualTo(2);assertThatThrownBy(()->webhooks.consume("fake",success,"00",context)).isInstanceOf(PaymentApiException.class).hasMessageContaining("signature");}

 @Test void duplicateFullRefundInvalidatesTicketsOnce(){Payment payment=payments.process(booking,attendee,"pay-refund","sandbox-success",context);seedTickets(booking,attendee,2);AuthenticatedActor actor=new AuthenticatedActor(attendee,Set.of("ATTENDEE"));Refund first=refunds.refund(payment.getId(),actor,"refund-once",List.of(),"Unable to attend",context);Refund duplicate=refunds.refund(payment.getId(),actor,"refund-once",List.of(),"Unable to attend",context);assertThat(duplicate.getId()).isEqualTo(first.getId());assertThat(paymentRepository.findById(payment.getId()).orElseThrow().getStatus()).isEqualTo(PaymentStatus.REFUNDED);assertThat(tickets.findAllByBookingId(booking)).allMatch(t->"REFUNDED".equals(t.getStatus()));assertThat(transactions.findAllByPaymentIdOrderByOccurredAt(payment.getId()).stream().filter(t->t.getType()==TransactionType.REFUND)).hasSize(1);}

 @Test void failedRefundCanBeRetriedWithANewKeyWithoutDuplicatingTheFailedAttempt(){Payment payment=payments.process(booking,attendee,"pay-refund-retry","sandbox-success-refund-fail-once",context);seedTickets(booking,attendee,2);AuthenticatedActor actor=new AuthenticatedActor(attendee,Set.of("ATTENDEE"));Refund failed=refunds.refund(payment.getId(),actor,"refund-failed",List.of(),"Unable to attend",context);Refund duplicate=refunds.refund(payment.getId(),actor,"refund-failed",List.of(),"Unable to attend",context);assertThat(failed.getStatus()).isEqualTo(RefundStatus.FAILED);assertThat(duplicate.getId()).isEqualTo(failed.getId());Refund retried=refunds.refund(payment.getId(),actor,"refund-retry",List.of(),"Unable to attend",context);assertThat(retried.getStatus()).isEqualTo(RefundStatus.SUCCEEDED);assertThat(paymentRepository.findById(payment.getId()).orElseThrow().getStatus()).isEqualTo(PaymentStatus.REFUNDED);assertThat(transactions.findAllByPaymentIdOrderByOccurredAt(payment.getId()).stream().filter(t->t.getType()==TransactionType.REFUND)).hasSize(2);}

 @Test void organizerCanPartiallyRefundButCheckedInTicketIsRejected(){Payment payment=payments.process(booking,attendee,"pay-partial","sandbox-success",context);List<PaymentTicketProjection> issued=seedTickets(booking,attendee,2);Refund partial=refunds.refund(payment.getId(),new AuthenticatedActor(organizer,Set.of("ORGANIZER")),"refund-partial",List.of(issued.get(0).getTicketId()),"Guest request",context);assertThat(partial.getAmount()).isEqualByComparingTo("25.00");assertThat(paymentRepository.findById(payment.getId()).orElseThrow().getStatus()).isEqualTo(PaymentStatus.PARTIALLY_REFUNDED);issued.get(1).checkedIn(Instant.now());tickets.save(issued.get(1));assertThatThrownBy(()->refunds.refund(payment.getId(),new AuthenticatedActor(organizer,Set.of("ORGANIZER")),"refund-checked-in",List.of(issued.get(1).getTicketId()),"No",context)).isInstanceOf(PaymentApiException.class).hasMessageContaining("Checked-in");}

 private UUID seedOrder(int quantity){UUID id=UUID.randomUUID();orders.save(new BookingPaymentOrder(id,attendee,UUID.randomUUID(),organizer,UUID.randomUUID(),UUID.randomUUID(),quantity,new BigDecimal("25.00"),new BigDecimal("25.00").multiply(BigDecimal.valueOf(quantity)),"USD",Instant.now().plus(Duration.ofDays(30)),Instant.now().plus(Duration.ofMinutes(15)),Instant.now()));return id;}
 private List<PaymentTicketProjection> seedTickets(UUID bookingId,UUID owner,int count){List<PaymentTicketProjection> result=new ArrayList<>();for(int i=0;i<count;i++)result.add(tickets.save(new PaymentTicketProjection(UUID.randomUUID(),bookingId,owner,UUID.randomUUID(),Instant.now())));return result;}
 private String sign(String body){try{Mac mac=Mac.getInstance("HmacSHA256");mac.init(new SecretKeySpec("test-webhook-secret".getBytes(StandardCharsets.UTF_8),"HmacSHA256"));return HexFormat.of().formatHex(mac.doFinal(body.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
}
