package com.eventplatform.payment.application;

import com.eventplatform.payment.api.*; import com.eventplatform.payment.domain.*; import com.eventplatform.payment.security.AuthenticatedActor; import java.util.*; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;

@Service
public class PaymentQueryService {
 private final PaymentRepository payments; private final PaymentAttemptRepository attempts; private final RefundRepository refunds; private final PaymentTransactionRepository transactions; private final BookingPaymentOrderRepository orders;
 public PaymentQueryService(PaymentRepository payments,PaymentAttemptRepository attempts,RefundRepository refunds,PaymentTransactionRepository transactions,BookingPaymentOrderRepository orders){this.payments=payments;this.attempts=attempts;this.refunds=refunds;this.transactions=transactions;this.orders=orders;}
 @Transactional(readOnly=true) public Payment required(UUID id,AuthenticatedActor actor){Payment p=payments.findById(id).orElseThrow(()->new PaymentApiException(HttpStatus.NOT_FOUND,"PAYMENT_NOT_FOUND","The payment was not found"));requireRead(p,actor);return p;}
 @Transactional(readOnly=true) public List<PaymentApi.PaymentResponse> list(AuthenticatedActor actor){return payments.findAllByAttendeeIdOrderByCreatedAtDesc(actor.id()).stream().map(this::map).toList();}
 @Transactional(readOnly=true) public PaymentApi.PaymentResponse get(UUID id,AuthenticatedActor actor){return map(required(id,actor));}
 @Transactional(readOnly=true) public List<PaymentApi.TransactionResponse> history(UUID id,AuthenticatedActor actor){required(id,actor);return transactions.findAllByPaymentIdOrderByOccurredAt(id).stream().map(t->new PaymentApi.TransactionResponse(t.getId(),t.getType(),t.getStatus(),t.getAmount(),t.getCurrency(),t.getProviderTransactionId(),t.getProviderEventId(),t.getFailureCode(),t.getOccurredAt())).toList();}
 public PaymentApi.PaymentResponse map(Payment p){List<PaymentApi.AttemptResponse> as=attempts.findAllByPaymentIdOrderByCreatedAt(p.getId()).stream().map(a->new PaymentApi.AttemptResponse(a.getId(),a.getStatus(),a.getProviderAttemptId(),a.getFailureCode(),a.getFailureReason(),a.getCreatedAt(),a.getUpdatedAt())).toList();List<PaymentApi.RefundResponse> rs=refunds.findAllByPaymentIdOrderByCreatedAt(p.getId()).stream().map(r->new PaymentApi.RefundResponse(r.getId(),r.getAmount(),r.getCurrency(),r.ticketIds(),r.getStatus(),r.getProviderRefundId(),r.getFailureCode(),r.getFailureReason(),r.getCreatedAt(),r.getUpdatedAt())).toList();return new PaymentApi.PaymentResponse(p.getId(),p.getBookingId(),p.getAttendeeId(),p.getEventId(),p.getAmount(),p.getRefundedAmount(),p.getCurrency(),p.getProvider(),p.getProviderPaymentId(),p.getStatus(),p.getFailureCode(),p.getFailureReason(),p.getCreatedAt(),p.getUpdatedAt(),p.getPaidAt(),as,rs);}
 private void requireRead(Payment p,AuthenticatedActor actor){if(p.getAttendeeId().equals(actor.id())||actor.hasRole("ADMIN"))return;BookingPaymentOrder order=orders.findById(p.getBookingId()).orElseThrow();if(actor.hasRole("ORGANIZER")&&order.getEventOrganizerId().equals(actor.id()))return;throw new PaymentApiException(HttpStatus.FORBIDDEN,"PAYMENT_ACCESS_DENIED","This payment is not visible to the caller");}
}
