package com.eventplatform.payment.application;

import com.eventplatform.payment.api.*; import com.eventplatform.payment.domain.*; import com.eventplatform.payment.integration.PaymentLifecycleEvents; import com.eventplatform.payment.outbox.PaymentTransactionalOutbox; import com.eventplatform.payment.provider.PaymentProvider; import com.eventplatform.payment.security.AuthenticatedActor;
import java.math.BigDecimal; import java.time.*; import java.util.*; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;

@Service
public class RefundStateService {
 public record ClaimedRefund(Refund refund,Payment payment,boolean existing){}
 private final PaymentRepository payments; private final RefundRepository refunds; private final BookingPaymentOrderRepository orders; private final PaymentTicketProjectionRepository tickets; private final PaymentTransactionRepository transactions; private final PaymentTransactionalOutbox outbox; private final Clock clock;
 public RefundStateService(PaymentRepository payments,RefundRepository refunds,BookingPaymentOrderRepository orders,PaymentTicketProjectionRepository tickets,PaymentTransactionRepository transactions,PaymentTransactionalOutbox outbox,Clock clock){this.payments=payments;this.refunds=refunds;this.orders=orders;this.tickets=tickets;this.transactions=transactions;this.outbox=outbox;this.clock=clock;}
 @Transactional public ClaimedRefund claim(UUID paymentId,AuthenticatedActor actor,String key,List<UUID> requestedTickets,String reason){
  validateKey(key);Payment payment=payments.findByIdForUpdate(paymentId).orElseThrow(()->new PaymentApiException(HttpStatus.NOT_FOUND,"PAYMENT_NOT_FOUND","The payment was not found"));Refund prior=refunds.findByRequestedByAndIdempotencyKey(actor.id(),key).orElse(null);if(prior!=null){if(!prior.getPaymentId().equals(paymentId)||!Objects.equals(prior.getReason(),reason)||(requestedTickets!=null&&!requestedTickets.isEmpty()&&!new HashSet<>(prior.ticketIds()).equals(new HashSet<>(requestedTickets))))throw conflict();return new ClaimedRefund(prior,payment,true);}if(payment.getStatus()!=PaymentStatus.SUCCEEDED&&payment.getStatus()!=PaymentStatus.PARTIALLY_REFUNDED)throw new PaymentApiException(HttpStatus.CONFLICT,"PAYMENT_NOT_REFUNDABLE","Only a settled payment can be refunded");
  BookingPaymentOrder order=orders.findById(payment.getBookingId()).orElseThrow();Instant now=clock.instant();if(!order.getEventStartsAt().isAfter(now))throw new PaymentApiException(HttpStatus.CONFLICT,"REFUND_WINDOW_CLOSED","Refunds close when the event starts");
  boolean owner=payment.getAttendeeId().equals(actor.id())&&actor.hasRole("ATTENDEE");boolean organizer=order.getEventOrganizerId().equals(actor.id())&&actor.hasRole("ORGANIZER");boolean admin=actor.hasRole("ADMIN");if(!owner&&!organizer&&!admin)throw new PaymentApiException(HttpStatus.FORBIDDEN,"REFUND_NOT_AUTHORIZED","Only the attendee, event organizer, or an administrator may refund this payment");
  List<PaymentTicketProjection> all=tickets.findAllByBookingId(payment.getBookingId());if(all.size()!=order.getQuantity())throw new PaymentApiException(HttpStatus.CONFLICT,"TICKET_PROJECTION_NOT_READY","Ticket issuance has not completed; retry the refund later");List<PaymentTicketProjection> available=all.stream().filter(t->!"REFUNDED".equals(t.getStatus())).toList();
  List<UUID> selected=requestedTickets==null||requestedTickets.isEmpty()?available.stream().map(PaymentTicketProjection::getTicketId).toList():requestedTickets.stream().distinct().sorted().toList();
  if(owner&&selected.size()!=available.size())throw new PaymentApiException(HttpStatus.FORBIDDEN,"ATTENDEE_FULL_REFUND_ONLY","Attendees may request only a full remaining refund");
  Map<UUID,PaymentTicketProjection> byId=new HashMap<>();available.forEach(t->byId.put(t.getTicketId(),t));if(selected.isEmpty()||selected.stream().anyMatch(id->!byId.containsKey(id)))throw new PaymentApiException(HttpStatus.BAD_REQUEST,"REFUND_TICKETS_INVALID","Refund tickets must be active tickets from this booking");
  if(selected.stream().map(byId::get).anyMatch(t->"CHECKED_IN".equals(t.getStatus())))throw new PaymentApiException(HttpStatus.CONFLICT,"CHECKED_IN_TICKET_NOT_REFUNDABLE","Checked-in tickets cannot be refunded");
  BigDecimal amount=order.getUnitPrice().multiply(BigDecimal.valueOf(selected.size()));if(amount.compareTo(payment.refundableAmount())>0)throw new PaymentApiException(HttpStatus.CONFLICT,"REFUND_AMOUNT_EXCEEDED","The refund exceeds the remaining payment balance");
  Refund refund=refunds.save(new Refund(UUID.randomUUID(),paymentId,payment.getBookingId(),actor.id(),key,amount,payment.getCurrency(),selected,reason,now));return new ClaimedRefund(refund,payment,false);
 }
 @Transactional public Refund claimCompensation(UUID paymentId,String key,RequestContext context){Payment payment=payments.findByIdForUpdate(paymentId).orElseThrow();Refund prior=refunds.findByRequestedByAndIdempotencyKey(payment.getAttendeeId(),key).orElse(null);if(prior!=null){if(!prior.getPaymentId().equals(paymentId))throw conflict();return prior;}Instant now=clock.instant();return refunds.save(new Refund(UUID.randomUUID(),paymentId,payment.getBookingId(),payment.getAttendeeId(),key,payment.refundableAmount(),payment.getCurrency(),List.of(),"Saga compensation: inventory could not be confirmed",now));}
 @Transactional public Refund apply(UUID refundId,PaymentProvider.ProviderResult result,RequestContext context){Refund refund=refunds.findById(refundId).orElseThrow();Payment payment=payments.findByIdForUpdate(refund.getPaymentId()).orElseThrow();if(refund.getStatus()!=RefundStatus.PROCESSING)return refund;BookingPaymentOrder order=orders.findById(payment.getBookingId()).orElseThrow();Instant now=clock.instant();if(result.outcome()==PaymentProvider.Outcome.SUCCEEDED){refund.succeed(result.providerObjectId(),now);payment.refunded(refund.getAmount(),now);refund.ticketIds().forEach(id->tickets.findById(id).ifPresent(t->t.refunded(now)));transactions.save(new PaymentTransaction(UUID.randomUUID(),payment.getId(),null,refund.getId(),TransactionType.REFUND,TransactionStatus.SUCCEEDED,refund.getAmount(),refund.getCurrency(),result.transactionId(),null,null,now));boolean full=payment.getStatus()==PaymentStatus.REFUNDED;outbox.append("Refund",refund.getId(),PaymentLifecycleEvents.REFUNDED,new PaymentLifecycleEvents.RefundChangedV1(refund.getId(),payment.getId(),payment.getBookingId(),payment.getAttendeeId(),payment.getEventId(),refund.getAmount(),refund.getCurrency(),refund.ticketIds(),full,null,null,order.getEventTitle(),order.getEventStartsAt(),order.getAttendeeEmail(),order.getAttendeePhone(),order.getAttendeeLocale(),now),context,now);}else if(result.outcome()==PaymentProvider.Outcome.FAILED){refund.fail(result.providerObjectId(),result.failureCode(),result.failureReason(),now);transactions.save(new PaymentTransaction(UUID.randomUUID(),payment.getId(),null,refund.getId(),TransactionType.REFUND,TransactionStatus.FAILED,refund.getAmount(),refund.getCurrency(),result.transactionId(),null,result.failureCode(),now));outbox.append("Refund",refund.getId(),PaymentLifecycleEvents.REFUND_FAILED,new PaymentLifecycleEvents.RefundChangedV1(refund.getId(),payment.getId(),payment.getBookingId(),payment.getAttendeeId(),payment.getEventId(),refund.getAmount(),refund.getCurrency(),refund.ticketIds(),false,result.failureCode(),result.failureReason(),order.getEventTitle(),order.getEventStartsAt(),order.getAttendeeEmail(),order.getAttendeePhone(),order.getAttendeeLocale(),now),context,now);}return refund;}
 private void validateKey(String key){if(key==null||key.isBlank()||key.length()>128)throw new PaymentApiException(HttpStatus.BAD_REQUEST,"IDEMPOTENCY_KEY_REQUIRED","A valid Idempotency-Key header is required");} private PaymentApiException conflict(){return new PaymentApiException(HttpStatus.CONFLICT,"IDEMPOTENCY_KEY_REUSED","The idempotency key belongs to another refund");}
}
