package com.eventplatform.attendee.domain;
public enum BookingSagaState { PAYMENT_PENDING, PAYMENT_PROCESSING, INVENTORY_CONFIRMATION_PENDING, CONFIRMED, PAYMENT_FAILED, COMPENSATION_PENDING, REFUND_PENDING, PARTIALLY_REFUNDED, REFUNDED, EXPIRED, CANCELLED }
